### ISSUE TITLE
[Proposal] Sort merged_pull_request_numbers numerically by default

### ISSUE THREAD

**Issue by ikesyo** [x-motemen/git-pr-release#51]
Currently if PR number's digit is increased (e.g. PRs are from 998 to 1001) the PRs are listed as follows:

- 1000
- 1001
- 998
- 999

due to the output order of `git ls-remote origin refs/pull/*/head`. How about sorting the numbers numerically? Or sorting at template is recommended?

https://github.com/x-motemen/git-pr-release/blob/fac882a8409fd5239a913c534ba9608bf73cc85e/lib/git/pr/release/cli.rb#L91-L108

**Comment by onk** [comment]
Alphabetical sort is not intended.

It seems good to have the same sort order as `git log --merges`, but numerically sort is better than alphabetically sort and is acceptable.

**Comment by yutailang0119** [comment]
I agree to sort by number.

**Comment by onk** [comment]
Released as v1.6.0.

**Comment by ikesyo** [comment]
Thanks 🎉
