### ISSUE TITLE
GitHub update causes titles to be rendered twice

### ISSUE THREAD

**Issue by nhosoya** [x-motemen/git-pr-release#65]
A recent update to GitHub seems to have changed the way PullRequest URLs are displayed when they are in descriptions or comments.
Specifically, if the Pull Request URL is in a checklist item, the title is now automatically completed.
(Perhaps [this update](https://github.com/features/issues) is related.)

This causes the title to be rendered twice in the description generated by git-pr-release using `to_checklist_item`.

---

```
https://github.com/x-motemen/git-pr-release/pull/1
```

This will be rendered as follows. (No change)

https://github.com/x-motemen/git-pr-release/pull/1

---

```
- [ ] https://github.com/x-motemen/git-pr-release/pull/1
```

If the item in the checklist has a URL of a Pull Request, the title will be rendered automatically.

- [ ] https://github.com/x-motemen/git-pr-release/pull/1

**Comment by astj** [comment]
I believe #66 is a super nice fix and I'm enjoying v1.8.0, but I've noticed GitHub does not expand issue title in their Slack integration.
Previously we can read what to be released via Slack, but now we have to open GitHub to check them. Hmm, trade-offs. 🤔 

![image](https://user-images.githubusercontent.com/5095045/125236902-be3b9800-e31f-11eb-90aa-9689f7e57cfc.png)
